"""empty message

Revision ID: 5c3f039498cc
Revises: cb0b754b2126
Create Date: 2021-06-07 18:58:31.113995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3f039498cc'
down_revision = 'cb0b754b2126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('collaborators', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'collaborators')
    # ### end Alembic commands ###
