"""empty message

Revision ID: cb0b754b2126
Revises: 0be8fcab3f5d
Create Date: 2021-06-07 10:19:46.892983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0b754b2126'
down_revision = '0be8fcab3f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('columnOrder', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('columns', sa.Column('todoOrder', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('columns', 'todoOrder')
    op.drop_column('boards', 'columnOrder')
    # ### end Alembic commands ###
